:linkcss:
:imagesdir: ./images
:stylesdir: stylesheets/
:stylesheet:  colony.css
:data-uri:


image::./practicals/pdfvarnam-ninnukori.pdf[]


== LESSON-I	LAKSHANA GITA
=== LESSON-II	SVARAJATI

Ragam: Bilahari (29th mela janyam)

Arohana:	s  r2  g3  p  d2  ṡ

Avarohana: ṡ  n3  d2   p  m1  g3   r2  s	Talam: Adi

Pallavi:

Raaraa Venugopa Baala Raajita Sadguna Jaya Sheela

Anupallavi:

Saarasaaksha Nera Memi Maarubaari Korvaleraa

Charanam 1:

Nandagopaalaa Ne Nendu Pojaalaa Nee

Vindu Raaraa Sadamalamadito Mudamala Raganaa Keduruga Gadiyara (Raaravenu)

Charanam 2:

Palumaa Runugaa Ravamuna Nin Pilachina Palukavu Nalugakuraa Karivarada Marimarina Adharamugro Larakani Karamuga (Raaravenu)

Charanam 3:

Raa Nagadara Raa Murahara Raa Bhavahara Raaveraa

Ee Maguvanu Ee Lalalanu Ee Sogasini Chekoraa

Korikalim Pondaa Dendamu Neeyanda Cherenu Neechenta Maruvakuraa Karamulache Marimari Ninu

Sharanane dara (Raaravenu)

Pallavi:


S ,  r,	G P,	D Ṡ,  N D		|   P d  p,	m g  r s,	r s  ṇ ḍ,		S ;	||

Raa-raa Venu   gopa Baala		Raa jita   Sad-guna   Jaya Shee-		la-

Anupallavi:

S ,  r	G P	M , g			P   D |   Ṙ , ṡ		N , d	P , m		G , r  ||
Saa-ra	saa ksha Ne-ra	Charanam 1:			Me mi	Maa-ru		baa-ri   Ko-rva		le-raa


S ,   r	G   G	G ;		;   r g	|	P ,	p		P P	P ;		;   dp		||
Nan-da  go paa	laa-		- Ne	Nen-du		Pojaa	laa-		- Nee-

Ṡ , ṡ	Ṡ	Ṡ	ġ ṙ ṡ n	n d  P  |   p d p m	g  g  R	g  p  m  g
Vindu	Raa raa   Sadamala	madi to	Mudamala   Ra ga naa   Keduruga
r  s r   g ||
Gadiyara || (Raaravenu)


==== Charanam 2:

p  p  P  r r   R	g  p m g	G ;	| g p  m  g	m g  r s	r g  r s	S ; ||

Palu maa Runugaa Ravamuna Nin-Pilachina	Palukavu Nalugaku raa-

r  s ṇ ḍ	S ;	m g  r g	P ;	|   d  p   d	ṙ	Ṡ  ;	ṙ

Karivara	da -	Marimari	naa-	A dha ramu  gro -   La raka

ṡ n  d	p m  g  r   ||	ni  Ka ra muga (Raaravenu)

==== Charanam 3:

P ;	m g  r g	D ;	m g  r g	|	P  ;	m g  r g	P  P	P ;	||

Raa	Nagadara	Raa	Mu rahara	Raa -   Bhavahara Raave	raa -

Ġ ;	ṙ  ṡ n  d	Ṙ ;	ṙ  ṡ  n d  |  Ṡ  ;	ṙ  ṡ   n	d	Ṡ  Ṡ	Ṡ ;	||

Ee -   Ma guvanu   Ee	Lala lanu	Ee  -	Sogasini	Cheko	raa

Ġ ṙ  ṡ	Ṙ  Ṙ	Ṙ ;	Ṙ  - ṡ n	|  D D	D ;	P  m g	G  G	||

Korika	lim Pon daa-   Den damu	Neeyan  da -   Cherenu   Neechen

G ;	s  r g  d	P ;	ṙ  ṡ ṙ ġ	| Ṡ ;  ġ ṙ  ṡ n   d  p - m g   r s   r g  ||

ta -  Maruvaku	raa-   Ka ramula	che  Marimari  Ninu Shara nane dara
(Raaravenu)

=== LESSON III

=== VARNAS

==== 1. Hamwsadwani
==== 2. Mohana
==== 3. Sankarabharanam


== KRITIS

=== 1. Shree Gananatham Bhajare +
Ragam: Eesha Manohari (28 mela janyam) +
ARO: s r g m p d n ṡ || +
AVA: ṡ n d p m g m r s || +
Talam: Rupakam	Composer: Muttuswami Dikshitar

==== Pallavi:

Shree Gananatham Bhajare Chita Paraashakthiyutham

==== Anupallavi:

Naaga Yagnya Suthradharam Nada Layaanandakaram

==== Charanam

Aagamaadi Sannutham Akhila Deva Pujitham +
Yogishaali Bhaavitham Bogishaali Sevitham +

==== Madhyamakala Sahityam:

Raagadweshaadi Rahita Ramaneeya Hrudaya Viditham +
Sri Guru Guha Sannutham Chinmoola Kamalaasthitham +

== 2. Koluvaiyunmade kodanda pani
Ragam : Devagandhari Talam : Adi
Composer: Tyagaraja

=== Pallavi:
koluvaiyunnade kodanda pani

=== Anupallavi:
Sa-lalita matulai sareku silulai valacucu
kori vacci sevimpare (koluvai)

=== Charanam 1
Janakaja bharatadulato manci naivedyambulu canuvuna
vedukanaraginci merupu kotla geru kanaka patamu
sommulanu dharinci vedoktambaina sanaka vacanamulace
toshinci asritula poshinci (koluvai)

=== Charanam 2
varamagu vasanalu parimalimpa sannidhilo velugucu
sura vara satulu baga natimpaadi gaka parasara
narada munulella nutimpayentento nenaruna sura pati
vagisulu sevimpa menu pulakarimpa (koluvai)

=== Charanam 3
udu raja mukhudu sesha sayya paini celangaga
kani pudami kumari su-gandhamu puyya nammina varalake
kada kantini korina varamiyya tyagaraju nenaruna
adugaduguku madupulanandiyya Sri ramayya (koluvai)

== 3. Paluke Bangara Mayena Kodandapani

Ragam - Anandabairavi	Talam - Adi

=== Pallavi:
Paluke bangaaramaayenaa kodhandapaani

=== Charanam:
Paluke bangaaramaaye pilachina palukavemi

Kalalo ni naama smaranaa maruvaa chakkani tandri ||

Iravuga isukalonaa poralina vuduta bhaktiki

Karuninchi brochitivani neranammitini tandri ||

Saranaagatatraana birudhaamkitudavu kaavaa

Karuninchu bhadhraachala vara raamadhaasaposaa ||

== 4. Vade Venkatadri
Raga: Vasanta	Tala: Adi	Composer: Annamayya

=== Pallavi :
Vade venkatadri mida vara deivamu +
Podimito podalupe podavaina dehamu +

=== Charanam 1 :

Okkokka roma kupananogi brahmanda +
kotulu vikatilla velukonde venutaivamu +
pakkanalu tanaloni podunalu lokalu +
doddi padana golice dodda daivamu +

=== Charanam 2 :
Sarusa shankha cakralu saribattiya	surula +
karagi padavesina gani deivamu	siri nuramuna +
nilpi shri venkateshudai +
sharanagatulagace shatamaina deivamu



=== Reference books

1.	South Indian Music books 1 to 6 volumes by P.Sambamurthy +
2.	Sangeetha Sastra Samgrahanam by P.K. Indrani +
3.	Ganamrutha Bodhini by A.S. Panchapakesa Iyer. +
4.	Ganamrutha Varnamalika by A.S. Panchapakesa Iyer. +
5.	Sangita vidya prakasika of Aakondi Srinivasa Rajarao +
6.	Great Composers - Book 1 & 2 by P.Sambamurthy +

