:linkcss:
:imagesdir: ./images
:stylesdir: stylesheets/
:stylesheet:  colony.css
:data-uri:

== LESSON-I	LAKSHANA GITA

Ragam: Hamsadhwani (29th mela janyam)	Talam: Triputa	Arohanam: s r₂ g₃ p n₃ ṡ	Avarohanam: ṡ n₃ p g₃ r₂ s

s , , | s , | ; || s r g | r , | s ṇ ||	aa . . | . . | . . || re . re | da . | kshi na ||

p ṇ s | r s | r g || p n s | r s | r g ||	pu ra ni | a . | . sa || dwa . ra | . ka | . . ||

p g r | g r | s ṇ || s r r | s , | s , ||	sri . ra | a ja | go o || pa . lu | re . | re . ||

ṇ s , | r g | r s || g r s | ṇ s | r g ||	cha tu . | sru thi | ri sha || Bha . , | an . | ta ra ||

p g p | g r | s r || g r , | s ṇ | s , ||	ga . . | dha . | . ra || cha tu . | sru ti | dai . ||

r	g , | s r | g , || p g p | g r | p g ||	va ta . | swa ra | ka . || ka li ni | sha . | . da ||	n p n | p g | r g || p n , | ṡ ṡ | ṡ n ||	i ta ra | su . | . dha || a . . | ro . | . ha ||

ṡ n ṡ | ṡ ṡ | ṡ n || p n ṡ | p n | ṡ n ||	a va ro | . . | . ha || ma da . | va . | rji ta ||

ṡ , ṡ | ṡ n | p g || n , n | p g | r s ||	sa . gra | ha . | . . || nya . . | sam . | . sa ||

s	r r | s s | r r || g p g | r s | r g ||	dhi . ra | shan ka | ra . || bha ra na | me . | . la ||

r g p | g r | s r || g r s | ṇ s | r s ||	tri pu ta | yu . | . kta || ja ni ta | ham . | sa . ||

r s ṇ | p ṇ | s ṇ || s r g | p n | ṡ n ||	dhwa ni . | ra . | . ga || ma va dha | a . | ra ya ||

p g r | s n | p ṇ || s r g | r r | s , ||	sri . . | ra . | . ma || na mo . | na . | mo . ||

=== LESSON-II	SVARAJATI

Ragam: Bilahari (29th mela janyam)

Arohana:	s  r2  g3  p  d2  ṡ

Avarohana: ṡ  n3  d2   p  m1  g3   r2  s	Talam: Adi

Pallavi:

Raaraa Venugopa Baala Raajita Sadguna Jaya Sheela

Anupallavi:

Saarasaaksha Nera Memi Maarubaari Korvaleraa

Charanam 1:

Nandagopaalaa Ne Nendu Pojaalaa Nee

Vindu Raaraa Sadamalamadito Mudamala Raganaa Keduruga Gadiyara (Raaravenu)

Charanam 2:

Palumaa Runugaa Ravamuna Nin Pilachina Palukavu Nalugakuraa Karivarada Marimarina Adharamugro Larakani Karamuga (Raaravenu)

Charanam 3:

Raa Nagadara Raa Murahara Raa Bhavahara Raaveraa

Ee Maguvanu Ee Lalalanu Ee Sogasini Chekoraa

Korikalim Pondaa Dendamu Neeyanda Cherenu Neechenta Maruvakuraa Karamulache Marimari Ninu

Sharanane dara (Raaravenu)

Pallavi:


S ,  r,	G P,	D Ṡ,  N D		|   P d  p,	m g  r s,	r s  ṇ ḍ,		S ;	||

Raa-raa Venu   gopa Baala		Raa jita   Sad-guna   Jaya Shee-		la-

Anupallavi:

S ,  r	G P	M , g			P   D |   Ṙ , ṡ		N , d	P , m		G , r  ||
Saa-ra	saa ksha Ne-ra	Charanam 1:			Me mi	Maa-ru		baa-ri   Ko-rva		le-raa


S ,   r	G   G	G ;		;   r g	|	P ,	p		P P	P ;		;   dp		||
Nan-da  go paa	laa-		- Ne	Nen-du		Pojaa	laa-		- Nee-

Ṡ , ṡ	Ṡ	Ṡ	ġ ṙ ṡ n	n d  P  |   p d p m	g  g  R	g  p  m  g
Vindu	Raa raa   Sadamala	madi to	Mudamala   Ra ga naa   Keduruga
r  s r   g ||
Gadiyara || (Raaravenu)


==== Charanam 2:

p  p  P  r r   R	g  p m g	G ;	| g p  m  g	m g  r s	r g  r s	S ; ||

Palu maa Runugaa Ravamuna Nin-Pilachina	Palukavu Nalugaku raa-

r  s ṇ ḍ	S ;	m g  r g	P ;	|   d  p   d	ṙ	Ṡ  ;	ṙ

Karivara	da -	Marimari	naa-	A dha ramu  gro -   La raka

ṡ n  d	p m  g  r   ||	ni  Ka ra muga (Raaravenu)

==== Charanam 3:

P ;	m g  r g	D ;	m g  r g	|	P  ;	m g  r g	P  P	P ;	||

Raa	Nagadara	Raa	Mu rahara	Raa -   Bhavahara Raave	raa -

Ġ ;	ṙ  ṡ n  d	Ṙ ;	ṙ  ṡ  n d  |  Ṡ  ;	ṙ  ṡ   n	d	Ṡ  Ṡ	Ṡ ;	||

Ee -   Ma guvanu   Ee	Lala lanu	Ee  -	Sogasini	Cheko	raa

Ġ ṙ  ṡ	Ṙ  Ṙ	Ṙ ;	Ṙ  - ṡ n	|  D D	D ;	P  m g	G  G	||

Korika	lim Pon daa-   Den damu	Neeyan  da -   Cherenu   Neechen

G ;	s  r g  d	P ;	ṙ  ṡ ṙ ġ	| Ṡ ;  ġ ṙ  ṡ n   d  p - m g   r s   r g  ||

ta -  Maruvaku	raa-   Ka ramula	che  Marimari  Ninu Shara nane dara
(Raaravenu)

=== LESSON III

=== VARNAS

==== 1. Jalajakshi

Ragam:	Hamsadhwani (29th mela janyam) +
Talam:	Adi +
Composer:	Maanambuchaavadi Venkatasubbaiyer +

Arohanam:	s  r2  g3 p n3  ṡ
Avarohanam: ṡ n3  p  g3   r2  s +
Pallavi:	Jalajakshi ninnedabasi chala marulu konnadira +
Anupallavi:	Chelia nela ravademira cheluvudaina Sree Vendatesa +
Charanam:	Nee sati doranegana +

Pallavi: +
g	,	r  ,	s	,	,	,	ṇ	s	r	g	r	r	s	ṇ |
Ja  -   la   -	ja	-	-  -	kshi   -	-	-	ni	-	-	- |
s	r	s	s	ṇ	p	ṇ	s  |	r	p	,	ṇ	,	s	,	r  ||
nne  -	-	-	-	-	da	-   |	-	ba   -	-	-	si	-	-  ||
g	r	s	ṇ	s	r	p	ṇ	s	r	g	p	g	n	p	,	|
Cha  -	-	la	-	-	ma   -	-	-  ru	-	-	-	lu	-  |
ṡ	n	ṡ	ṙ	,	ṡ	n	p	|	p	g	,	r	,	s   ,	r   ||	ko	-	-	-	-	nna   -	-	|	-	di	-	-	-	ra   -	-   ||
36	Sri Padmavati Mahila Visvavidyalayam
Anupallavi:

p   g	r	s	ṇ	s	r	,	g	,	r	r	s	s	ṇ	p |	Che  -	-	li	-  -	ya	-   ne	-	la	-	-	- |
ṇ	s	r	g	,	s	g	r	|	g	p	,-	n	ṡ	,	,	, ||	Ra	-	-	-	-	va	de	-   |	-	-	-	mi	ra	-   -	- ||
ṙ	ṡ	n	p	n	ṡ	ṙ   ġ	ṡ	ṙ	ġ	ṗ	ġ	ṙ   ṡ   n   |	Che  -	-	lu	-  -	vu	dai   -	-	-	na  -	-	- |
ṙ	ṙ	,	ṡ	n	p	p	g	|	,	r	s	ṇ	p	ṇ	s	r  ||
sree  -	-   ven	-	-	ka   te   |	-	sa	-	-	-	-	-	-  ||	Mukthayi Svaram:
g	,	r	g	r	s	r	,	ṇ	s	r	g	r	r	s	ṇ  |	r	,-   ṇ	g	r	ṇ	s	r	|	p	ṇ	s	r	g	,	,-	p  ||
g	r	s	r	,	g	p	n	r	g	p	ṇ	s	r	g	p  |	p	ṇ	s	r	,	g	p	n  |	r	g	p	n	ṡ   ,	,	ṙ ||
ṙ	ṡ   n	p	,	n	ġ	ṙ	ṡ	n	,-	p	n	ṡ   ṙ	ġ |	p	,	n	ṡ	,-	ṙ	ġ ṙ	|   p	n	ṡ   ṙ	ġ	ṙ	n	ṙ ||	ġ	ṗ	ġ	ṙ   ṡ   n	ṡ   ṙ	ṡ   n	p	g	r	g	p	n   |	ġ	ṙ,-	ṡ	n	p	ṙ	ṡ	|	,-	n	p	g	,-	r	s	r  ||
(Ja)



Charanam:




n	,	,	,	,	,- ṡ   ,	ṙ	,	ṡ	n	p	p	g	r  |	Nee -   -	-	-	-  sa	-	-	-	ti	-	-	do	-	-
g	,	,-	g	r	s	r	,	|	r	s	ṇ	s	r	g	,	p  ||
ra	-	-	-	-	-   ne	-	|	-	-	-	ga	-   na  .	.	||
-



Chittai Svaras (1):

n	,	,-	p ,	,-	g	,	,	r	,	,	s	,	ṇ	, |
p   ,	,-	r	,	,-	ṇ	,   |	,-	s	,	r	,-	g	,	p   ||

(Nee)
Chittai Svaras (2):
n	,	p	g	r	s	r	,	g	r	s	ṇ	p	,-	r	ṇ- |
g	r	ṇ	p	ṇ	s	r	,| r	g	ṇ	s	r	g	p	||
(Nee)
Chittai Svaras (3):

n	p	g	r	ṇ	g	r	ṇ	p	ṇ	p   s	ṇ	r	s	g |	r	p	g	n	p	ṡ   n	ṙ   |	n	ġ	ṙ	n	ṙ	n	p	g||
p	n	ṡ   ṙ	ġ	g	p	n	ṡ   ṙ	r	g	p	n	ṡ   n |
ġ	ṙ	ṡ   n	p	ṙ	ṡ   n	|	p	g	r	ṇ	s	r	g	p||

(Nee)
Chittai Svaras (4):

ṡ   ,	,	,	,	,	n	ṙ	ṡ	n	p	g	r	s	r   g |	p	,	,	,	,	,	ṡ   n	|	p	g	r	s	r	g	p	n||
ṡ   ṙ	,-	n	ṙ	n	p	g	p	r  ,-g   p	g	r	s |
r	ṇ	,-	g	r	p	g	n	|	r	g	p	n	ṡ	,	,	, ||	n	p	g	p	,	,-	r	g	p	n	,-	g	p	n	ṡ   ṙ |	p	n	ṡ   ṙ	,	ġ	n	ṡ   |	n	ġ	ṙ   ṙ	n	,	p	n||	ġ	ṙ   ,-	n	ṡ   ṙ   ṗ	ġ	,	ṙ	ṡ   n	p	n	ṡ   ṙ |
ṡ	,	,-	p	,	,	n	p	|	g   r	s	ṇ	s	r	g	p||

(Nee)


=== 2. Ninnukori

Ragam:	Mohanam (28th Mela Janyam)
Talam:	Adi
Composer:	Ramnad Sreenivasa Iyengar
Arohanam : S R2 G2 P D2 ṡ	Avarahonam : ṡ D2 P G2 R2 S
Pallavi:	Ninnu kori yunna nura Nikila loka nayaka
Anupallavi: Nannu palimpa samayamura Nameetha krupa judara
Charanam:  Sannuthanga Sreenivasa

Pallavi:
g   ,	g	,	r   ,	,	,	s   s   r   r	g	g	r   r |	Nin -  nu   -	ko  -  -  -	ri	-   -   -	-	-   -	- |
s   r	g	r	s   r	s   ḍ  |   s   r	g	p	g	r	s   r   ||
Yu  -	-	-	nna -	-	-  |	nu   -	-	-	ra	-	-	- ||
g	p   g   g	r	s-   r   g	r	r	s   ḍ	s   r	g	r  |	Ni   -  -   -	-   -	ki   -	-   -   -   -  la	-	-   - |
g	p   g-  p	d	p-	d   ṡ  |   d   d	p-  g	d	p	g	r	||	lo	-  -   ka	-	-	na   - | -   -   -	ya	-	-   ka   - ||

Anupallavi:

g	,	g	, p	,	,	,	g	g	p	p d	d	p	,   |
Nan -  nu  -			pa   -  -  -	li	-   -   -			-   im   pa	- |

d	ṡ   d	d		p   g-   d	p	|  d-  g	d	p			g	r	s   r	||

Sa   -   -  -		-   -  ma	-	| -   ya	-   -			mu   -  ra	- ||

g	g	p	p		d	p- d   ṡ	d	ṡ   ṙ   ṡ		ġ   ṙ   ,	ṡ   |

Na  -   -	-		-   -  mee   -  -  tha	-   -		kru -	-  pa |

d	ṡ   ṙ   ṡ		,   d   p	d		|   ṡ   d	,	p			g	r	s   r	||

-	-	ju	-		-  -  -   -		|	da   -   -   -		ra   -   -   - ||

Mukthayi Svaram:

g	,	r   g	r   s   r   ,		s   r   s   g		r   g	s   r |

s   ḍ   s   r	g	r	g   p   |		g	p	d	,			p	,	,	,  ||

g   p   d   p	d   ṡ   ṙ  g		ṙ  ,   ġ -  ṡ   ,  ṙ -   d   , |

ṡ p	,	d	ṡ   ṙ   ġ  ṡ   |		,	d	p	,	g	r	s	r ||

Charanam:
g	,	g	,	g	,	,	,  r   g	p	g	p	,	,	,	|

San -  nu  -	tha   -   -   -		nga	-   -  -	Sree -  -	-  |


g	g	d   p	d	,-	g	d   |	d	p-  g   p	g	r	s   r   ||
ni   -   -	-	-	-	va	-  |	-	-	sa   -	-	-	-	-  ||

=== Chitta Svaram (1):
g	,	,	,	r   ,	s   ,	r   ,	,	,	ḍ   ,	,	,	| +
r   ,	ḍ   ,	s   ,	,	,	|	r   ,	,	,	g	,	r	, || +

(San)

===  Chitta Svaram (2)
g	,	g-   r	g	r   s   r	g	,	g-   p	ḍ   ḍ   s   r | +
g	,	g-	g	d	p	g	r	| g	,	g-ṡ	d	p	g	r  || +
(San)

=== Chitta Svaram (3)

p	,	d	d	p	,	g	r	s   ,	r   g	r   ,	s   ḍ |

s   ,	r   g	p	,	d	,	| ṡ   ṡ ,  -d	p	,	g	r  ||

(San)

=== Chitta Svaram (4)

ṡ   ,	ṙ   ġ	ṙ   ṡ   ṙ   ṡ	d	ṡ   d	p	g	r   s   r | +
s	,	,	,	,  ,	s   s |	r	r	g	g	p	p	d	d  || +

ṡ  ṙ   ġ	ṙ	ġ	ṙ	- d  ṡ	ṙ   ṡ	ṙ   ṡ	p	d	ṡ   d	|
ṡ d-  g	p	d p	d   p	|	ṙ   ṡ	d	p	g	r	s   r  ||
(San)

== LESSON V
=== 3. Sami nine kori

Ragam: Sankara bharanam (29th melakartha ragam) +
Talam: Adi +
Composer: Veenai Kuppaiyer +
Arohanam: S R2 G2 M1 P D2 N2 S +
Avarohanam: S N2 D2 P M1 G2 R2 S +

Pallavi: Sami nine kori chala marulu konnadira +
Anupallavi: Thamasamu seyaka dyajudara kumara +
Charanam: Neerajakshi neepai +

Pallavi

ṡ ,  ,  ,  n  ṡ d  n	p  ,- m   p   g   ,   m   ,   | +
Sa - - - -  -   - -	mi -  -   -   ni - - - |	p ,- d n p ,- d n | ṡ ṙ - ṡ n   d   p  d n ||	nne - - - - - ko - | -  -	-  -  -   -   ri - ||	ṡ ,-	ṡ d  p  m  p ,  p  m  g  r s r g  s |

Cha - la -  -  - ma - ru - - -  lu - - - |	ṇ - p ḍ ṇ s ,-	p	m   | g  r- g  m  p ,- d  n || +
---ko - - - - -  nna	- | - -	di - ra -   -   - ||

Anupallavi

s ,- d  d p m- d p , m- g  p- g ,  m   r |	Tha - - - -  -  - ma  -  s   - - -   -  - |	g m p-   d  d  p  m  p | d   n	ṡ  n   ṡ ,- ṙ  ġ ||	mu  -  - se -  -   -   -   | -  -   -   -   -  ka	- - ||	ṁ  ġ  ṙ - ṡ ṡ ṙ - ṡ n  d  p- d  n  ṡ ṙ - ṡ , |	Da - -  ya  - - ju   -  -  - da  - - -  ra - |	ṡ d  p- p , m   g   r | s  m   g   m   p ,  d   n ||
- -  - ku - - -  - | ma	- -  -   ra -  -   - ||

Mukthayi Svaram
ṡ r n ṡ d n ṡ - p d n ṡ - d p m- p d | m p- g m p- r g m | s r g m p d n ṡ ||	ṙ ġ ṁ ġ ṙ - ġ ṙ ṡ n- p d n ṡ , p , | ṡ n d p ,- m g r | s r , g m p d n || (Sa)

Charanam
p ,   d   n   ṡ -  ṡ	n	d   p  m  g   r  g , m , |	Nee - -  -  -  ra	-	- ja -  -   -  -  -  - - |	p ,	m-   d , p- ṡ n | d   p	m- g  m   r g  m ||
Kshi - - nee	-   -  pai - | -   -	-	-	-	-	-	- ||

Chittai Svaram (1)
p , ,- m , ,- p , ,- g , m ,- r , g | s , ,- r , ,- ṇ , | ,- s , r ,- g , m || (Nee)

Chittai Svaram (2)

p d , p m g- m p ,- m g m r g , r| s ṇ - ḍ ṇ ,- p ḍ ṇ | s r ,- ṇ s r g m || (Nee)

Chittai Svaram (3)

m , d p m g m , p- g m r g s , ṇ | s m g r s ṇ ḍ ṇ | s r g m p ,- g m ||	p d n- p d n ṡ ṙ ṡ ġ ṙ , ṡ n- d n | ṡ ,- ṙ n d p ,- d | m g r s ,- r g m || (Nee)	Chittai Svaram (4)
p , m p g m r g s ,- m g r s ṇ - p | ḍ ,- ṇ s r s ṇ , | s r g m p ,- d p ||	ṡ , n- ṙ , ṡ - ṁ ġ ṙ ġ - ṡ , n- p d n | ṡ , ṡ , n d p , | m g r s ,- r g m || (Nee)

== KRITIS

=== 1. Shree Gananatham Bhajare +
Ragam: Eesha Manohari (28 mela janyam) +
ARO: s r g m p d n ṡ || +
AVA: ṡ n d p m g m r s || +
Talam: Rupakam	Composer: Muttuswami Dikshitar

==== Pallavi:

Shree Gananatham Bhajare Chita Paraashakthiyutham

==== Anupallavi:

Naaga Yagnya Suthradharam Nada Layaanandakaram

==== Charanam

Aagamaadi Sannutham Akhila Deva Pujitham +
Yogishaali Bhaavitham Bogishaali Sevitham +

==== Madhyamakala Sahityam:

Raagadweshaadi Rahita Ramaneeya Hrudaya Viditham +
Sri Guru Guha Sannutham Chinmoola Kamalaasthitham +

== 2. Koluvaiyunmade kodanda pani
Ragam : Devagandhari Talam : Adi
Composer: Tyagaraja

=== Pallavi:
koluvaiyunnade kodanda pani

=== Anupallavi:
Sa-lalita matulai sareku silulai valacucu
kori vacci sevimpare (koluvai)

=== Charanam 1
Janakaja bharatadulato manci naivedyambulu canuvuna
vedukanaraginci merupu kotla geru kanaka patamu
sommulanu dharinci vedoktambaina sanaka vacanamulace
toshinci asritula poshinci (koluvai)

=== Charanam 2
varamagu vasanalu parimalimpa sannidhilo velugucu
sura vara satulu baga natimpaadi gaka parasara
narada munulella nutimpayentento nenaruna sura pati
vagisulu sevimpa menu pulakarimpa (koluvai)

=== Charanam 3
udu raja mukhudu sesha sayya paini celangaga
kani pudami kumari su-gandhamu puyya nammina varalake
kada kantini korina varamiyya tyagaraju nenaruna
adugaduguku madupulanandiyya Sri ramayya (koluvai)

== 3. Paluke Bangara Mayena Kodandapani

Ragam - Anandabairavi	Talam - Adi

=== Pallavi:
Paluke bangaaramaayenaa kodhandapaani

=== Charanam:
Paluke bangaaramaaye pilachina palukavemi

Kalalo ni naama smaranaa maruvaa chakkani tandri ||

Iravuga isukalonaa poralina vuduta bhaktiki

Karuninchi brochitivani neranammitini tandri ||

Saranaagatatraana birudhaamkitudavu kaavaa

Karuninchu bhadhraachala vara raamadhaasaposaa ||

== 4. Vade Venkatadri
Raga: Vasanta	Tala: Adi	Composer: Annamayya

=== Pallavi :
Vade venkatadri mida vara deivamu +
Podimito podalupe podavaina dehamu +

=== Charanam 1 :

Okkokka roma kupananogi brahmanda +
kotulu vikatilla velukonde venutaivamu +
pakkanalu tanaloni podunalu lokalu +
doddi padana golice dodda daivamu +

=== Charanam 2 :
Sarusa shankha cakralu saribattiya	surula +
karagi padavesina gani deivamu	siri nuramuna +
nilpi shri venkateshudai +
sharanagatulagace shatamaina deivamu



=== Reference books

1.	South Indian Music books 1 to 6 volumes by P.Sambamurthy +
2.	Sangeetha Sastra Samgrahanam by P.K. Indrani +
3.	Ganamrutha Bodhini by A.S. Panchapakesa Iyer. +
4.	Ganamrutha Varnamalika by A.S. Panchapakesa Iyer. +
5.	Sangita vidya prakasika of Aakondi Srinivasa Rajarao +
6.	Great Composers - Book 1 & 2 by P.Sambamurthy +

